services:
  redis:
    image: redis:alpine
    container_name: file_manager_redis
    restart: unless-stopped
    ports:
      - 6379:6379

  mongo:
    image: mongo:latest
    container_name: file_manager_mongo
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
